### ISSUE TITLE
fiber/v2

### ISSUE THREAD

**Issue by podanypepa** [Shareed2k/goth_fiber#1]
Don't work with `fiber/v2`

**Comment by zafhiel** [comment]
this project was abandoned?

**Comment by bhayes-zd** [comment]
Hey @Shareed2k 👋  Just adding onto this. Would love to see an upgrade to `fiber/v2`. It should be fairly painless. I believe it would require switching some error returns to `fiber.Handler` returns as well as obviously updating the go.mod/package imports to reference `github.com/gofiber/fiber/v2`.

Hope this is helpful. This is a great project and definitely worth keeping alive. ❤️

**Comment by Shareed2k** [comment]
Np wil try to find a time on this week

**Comment by podanypepa** [comment]
🙏 cool
