### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by dexbyte** [Shareed2k/goth_fiber#4]
The program crashes after calling the `\auth\callback` with an error
```
could not find a matching session for this request
```
This is the callback url I am using `http://127.0.0.1:8088/auth/callback?provider=google`

what went wrong?

**Comment by Shareed2k** [comment]
hi sorry for late answer, but this is callback endpoint, this endpoint is for provider redirect, you need first call `http://127.0.0.1:8088/login?provider=google` it will redirect you to provider and after login provider will use callback to redirect back...

![blog-open1](https://i2.wp.com/blogs.innovationm.com/wp-content/uploads/2019/07/blog-open1.png)
